#!/bin/bash
echo "choisissez une option"
echo -e  "1) ajouter utilisateur \n 2) supprimer utilisateur \n  3)retourner au menu précédent"
regex="^[A-Za-z]+" #affecte à une valeur regex toutes les lettres de l'alphabet

read opt #on lit la variable opt et on écrit dedans
if [[ "$opt" =~ $regex ]] #on test si opt est égal à regex
then
echo "its not an integer" #on affiche que ce n'est pas un integer si opt est une lettre
echo -e "1) ajouter utilisateur \n 2) supprimer utilisateur \n  3)retourner au menu précédent"
#on affiche le menu puis on relance opt
read opt
while [[ $opt -lt 3 ]] #une boucle tant la valeur opt est inférieur à 3
do
case $opt in 
#si opt=1 ajouter utilisateur
1) ./M1-1; echo -e "1) ajouter utilisateur \n 2) supprimer utilisateur \n  3)retourner au menu précédent";;
# si opt=2 supprimer utilisateur
2) read user ; deluser $user>../table/utilisateur_table; echo -e "1) ajouter utilisateur \n 2) supprimer utilisateur \n  3)retourner au menu précédent";;


esac 
read opt #lire de nouveau opt après l'utilitaire'

done
fi
./M5-1
